//! In-process hosts on loopback: identify exchange + TCP-only default transport.

#![allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::panic,
    clippy::single_match
)]

use std::time::Duration;

use cc_libp2p::reexport::{Keypair, Multiaddr, PeerId, Swarm, SwarmEvent, identify};
use cc_libp2p::{
    BehaviourConfig, CcBehaviour, CcBehaviourEvent, SwarmConfig, TransportConfig, build_swarm,
    quic_feature_is_compiled,
};
use futures::StreamExt;
use tokio::time::timeout;

fn make_swarm() -> (PeerId, Swarm<CcBehaviour>) {
    let keypair = Keypair::generate_secp256k1();
    let peer_id = PeerId::from_public_key(&keypair.public());
    let behaviour = CcBehaviour::new(&keypair, BehaviourConfig::default()).expect("behaviour");
    let swarm = build_swarm(keypair, behaviour, &SwarmConfig::default()).expect("swarm");
    (peer_id, swarm)
}

fn identify_received_from(peer: PeerId, ev: &CcBehaviourEvent) -> bool {
    // Generated by #[derive(NetworkBehaviour)] on CcBehaviour.
    matches!(
        ev,
        CcBehaviourEvent::Identify(identify::Event::Received { peer_id, .. }) if *peer_id == peer
    )
}

#[tokio::test]
async fn two_hosts_exchange_identify() {
    let (id_a, mut swarm_a) = make_swarm();
    let (id_b, mut swarm_b) = make_swarm();

    swarm_a
        .listen_on("/ip4/127.0.0.1/tcp/0".parse().expect("addr"))
        .expect("listen a");

    let listen_addr = timeout(Duration::from_secs(5), async {
        loop {
            if let SwarmEvent::NewListenAddr { address, .. } = swarm_a.select_next_some().await {
                break address;
            }
        }
    })
    .await
    .expect("listen timeout");

    swarm_b.dial(listen_addr).expect("dial");

    let mut a_identified_b = false;
    let mut b_identified_a = false;
    let mut a_connected_b = false;
    let mut b_connected_a = false;

    timeout(Duration::from_secs(15), async {
        loop {
            tokio::select! {
                ev = swarm_a.select_next_some() => {
                    match ev {
                        SwarmEvent::ConnectionEstablished { peer_id, .. } if peer_id == id_b => {
                            a_connected_b = true;
                        }
                        SwarmEvent::Behaviour(ref bev) if identify_received_from(id_b, bev) => {
                            a_identified_b = true;
                        }
                        _ => {}
                    }
                }
                ev = swarm_b.select_next_some() => {
                    match ev {
                        SwarmEvent::ConnectionEstablished { peer_id, .. } if peer_id == id_a => {
                            b_connected_a = true;
                        }
                        SwarmEvent::Behaviour(ref bev) if identify_received_from(id_a, bev) => {
                            b_identified_a = true;
                        }
                        _ => {}
                    }
                }
            }
            if a_identified_b && b_identified_a && a_connected_b && b_connected_a {
                break;
            }
        }
    })
    .await
    .expect("identify/connect timeout");

    assert!(
        a_connected_b,
        "host A must observe B's PeerId via ConnectionEstablished"
    );
    assert!(
        b_connected_a,
        "host B must observe A's PeerId via ConnectionEstablished"
    );
    assert!(a_identified_b, "host A must receive identify from B");
    assert!(b_identified_a, "host B must receive identify from A");
}

#[tokio::test]
async fn default_transport_is_tcp_only() {
    assert!(quic_feature_is_compiled());
    let cfg = TransportConfig::default();
    assert!(
        !cfg.quic.enabled,
        "transport.quic.enabled must default to false"
    );

    let keypair = Keypair::generate_secp256k1();
    let behaviour = CcBehaviour::new(&keypair, BehaviourConfig::default()).expect("behaviour");
    let mut swarm = build_swarm(keypair, behaviour, &SwarmConfig::default()).expect("swarm");

    // QUIC multiaddr must not be accepted by a TCP-only transport.
    let quic_addr: Multiaddr = "/ip4/127.0.0.1/udp/0/quic-v1".parse().expect("quic addr");
    let err = swarm
        .listen_on(quic_addr)
        .expect_err("quic listen must fail");
    let msg = err.to_string();
    assert!(
        msg.contains("multiaddr")
            || msg.contains("Transport")
            || msg.contains("not support")
            || !msg.is_empty(),
        "unexpected error: {msg}"
    );

    // TCP still works.
    swarm
        .listen_on("/ip4/127.0.0.1/tcp/0".parse().expect("tcp"))
        .expect("tcp listen");
}
