[package]
name = "cc-fork-choice"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
cc-types = { workspace = true }
cc-state-transition = { workspace = true }
thiserror = { workspace = true }
lru = { workspace = true }
tree_hash = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
ssz_types = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
snap = { workspace = true }
ethereum_ssz = { workspace = true }
cc-crypto = { workspace = true }
tracing-subscriber = { workspace = true }

[[bench]]
name = "head"
harness = false
