[package]
name = "cc-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
alloy-primitives = { workspace = true }
ethereum_hashing = { workspace = true }
ethereum_ssz = { workspace = true }
ethereum_ssz_derive = { workspace = true }
fixedbitset = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
ssz_types = { workspace = true }
thiserror = { workspace = true }
tree_hash = { workspace = true }
tree_hash_derive = { workspace = true }
typenum = { workspace = true }

[dev-dependencies]
sha2 = { workspace = true }
cc-spec-tests = { workspace = true }
