[package]
name = "cc-chain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
name = "cc_chain"
path = "src/lib.rs"

[[bin]]
name = "cc-chain"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
cc-bootstrap = { workspace = true }
cc-config = { workspace = true }
cc-proto = { workspace = true }
getrandom = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
